
import React, { useState, useEffect, useMemo } from 'react';
import { supabase } from '../services/supabase';
import { EventRequest } from '../types';
import { Calendar, momentLocalizer } from 'react-big-calendar';
import moment from 'moment';
import 'moment/locale/he';
import 'react-big-calendar/lib/css/react-big-calendar.css';
import '../src/Calendar.css'; // Import the new custom calendar styles
import { emailService } from '../services/email';

moment.locale('he');
const localizer = momentLocalizer(moment);

// --- Helper Functions & Components ---

const statusTranslations: { [key: string]: string } = {
  pending: 'ממתין לאישור',
    confirmed: 'מאושר',
    };

    const statusStyles: { [key: string]: string } = {
      pending: 'bg-amber-100 text-amber-800 ring-amber-600/20',
        confirmed: 'bg-green-100 text-green-800 ring-green-600/20',
        };

        const EventItem = ({ event, onSelect }: { event: EventRequest, onSelect: (event: EventRequest) => void }) => (
          <tr onClick={() => onSelect(event)} className="hover:bg-slate-50/70 cursor-pointer transition-colors">
              <td className="px-6 py-4 whitespace-nowrap">
                    <div className="font-bold text-slate-800">{event.customerName}</div>
                          <div className="text-sm text-neutral-500">{event.email}</div>
                              </td>
                                  <td className="px-6 py-4 whitespace-nowrap text-slate-700">{new Date(event.eventDate).toLocaleDateString('he-IL')}</td>
                                      <td className="px-6 py-4 whitespace-nowrap text-slate-700">{event.location}</td>
                                          <td className="px-6 py-4 whitespace-nowrap text-center text-slate-700">{event.guestCount}</td>
                                              <td className="px-6 py-4 whitespace-nowrap text-center">
                                                    <span className={`px-3 py-1.5 text-xs font-bold rounded-full ring-1 ring-inset ${statusStyles[event.status] || 'bg-gray-100 text-gray-800'}`}>
                                                            {statusTranslations[event.status] || event.status}
                                                                  </span>
                                                                      </td>
                                                                        </tr>
                                                                        );

                                                                        const AdminDashboard: React.FC = () => {
                                                                          const [viewMode, setViewMode] = useState('calendar');
                                                                            const [requests, setRequests] = useState<EventRequest[]>([]);
                                                                              const [loading, setLoading] = useState(true);
                                                                                const [selectedEvent, setSelectedEvent] = useState<EventRequest | null>(null);

                                                                                  useEffect(() => {
                                                                                      loadRequests();
                                                                                          document.body.style.backgroundColor = '#f8fafc'; // slate-50
                                                                                              return () => { document.body.style.backgroundColor = '' };
                                                                                                }, []);

                                                                                                  const loadRequests = async () => {
                                                                                                      setLoading(true);
                                                                                                          const { data, error } = await supabase.from('event_requests').select('*').order('event_date', { ascending: true });
                                                                                                              if (error) console.error("Error loading requests:", error);
                                                                                                                  else setRequests(data as EventRequest[]);
                                                                                                                      setLoading(false);
                                                                                                                        };

                                                                                                                          const handleConfirmEvent = async () => {
                                                                                                                              if (!selectedEvent) return;
                                                                                                                                  const { error } = await supabase.from('event_requests').update({ status: 'confirmed' }).eq('id', selectedEvent.id);
                                                                                                                                      if (error) {
                                                                                                                                            console.error("Error updating status:", error);
                                                                                                                                                } else {
                                                                                                                                                      await emailService.sendApprovalEmail({
                                                                                                                                                              customer_name: selectedEvent.customerName,
                                                                                                                                                                      customer_email: selectedEvent.email,
                                                                                                                                                                              event_date: new Date(selectedEvent.eventDate).toLocaleDateString('he-IL'),
                                                                                                                                                                                      location: selectedEvent.location,
                                                                                                                                                                                              order_link: `/order/${selectedEvent.id}`,
                                                                                                                                                                                                    });
                                                                                                                                                                                                          loadRequests();
                                                                                                                                                                                                                setSelectedEvent(null);
                                                                                                                                                                                                                    }
                                                                                                                                                                                                                      };

                                                                                                                                                                                                                        const calendarEvents = useMemo(() => requests.map(req => ({
                                                                                                                                                                                                                            title: `${req.customerName} - ${req.location}`,
                                                                                                                                                                                                                                start: new Date(req.eventDate),
                                                                                                                                                                                                                                    end: new Date(req.eventDate),
                                                                                                                                                                                                                                        resource: req,
                                                                                                                                                                                                                                          })), [requests]);

                                                                                                                                                                                                                                            return (
                                                                                                                                                                                                                                                <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12" dir="rtl">
                                                                                                                                                                                                                                                      <div className="flex justify-between items-center mb-8">
                                                                                                                                                                                                                                                              <h1 className="text-4xl font-serif font-bold text-slate-900">ניהול אירועים</h1>
                                                                                                                                                                                                                                                                      <div className="flex items-center gap-2 p-1 rounded-full bg-slate-200/80">
                                                                                                                                                                                                                                                                                <button onClick={() => setViewMode('list')} className={`px-5 py-2.5 text-sm font-bold flex items-center gap-2 rounded-full transition-all ${viewMode === 'list' ? 'bg-white text-slate-900 shadow' : 'text-slate-500'}`}>
                                                                                                                                                                                                                                                                                            <i className='bx bxs-list-ul'></i> רשימה
                                                                                                                                                                                                                                                                                                      </button>
                                                                                                                                                                                                                                                                                                                <button onClick={() => setViewMode('calendar')} className={`px-5 py-2.5 text-sm font-bold flex items-center gap-2 rounded-full transition-all ${viewMode === 'calendar' ? 'bg-white text-slate-900 shadow' : 'text-slate-500'}`}>
                                                                                                                                                                                                                                                                                                                            <i className='bx bxs-calendar'></i> יומן
                                                                                                                                                                                                                                                                                                                                      </button>
                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                          {loading ? (
                                                                                                                                                                                                                                                                                                                                                                  <div className="text-center py-20 text-neutral-500">טוען נתונים...</div>
                                                                                                                                                                                                                                                                                                                                                                        ) : (
                                                                                                                                                                                                                                                                                                                                                                                <div className="bg-white rounded-3xl shadow-xl border border-neutral-100 p-1 sm:p-2">
                                                                                                                                                                                                                                                                                                                                                                                          {viewMode === 'list' ? (
                                                                                                                                                                                                                                                                                                                                                                                                      <div className="overflow-x-auto">
                                                                                                                                                                                                                                                                                                                                                                                                                    <table className="w-full text-right">
                                                                                                                                                                                                                                                                                                                                                                                                                                    <thead className="border-b border-neutral-100">
                                                                                                                                                                                                                                                                                                                                                                                                                                                      <tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <th className="px-6 py-4 text-sm font-bold text-slate-500">לקוח</th>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <th className="px-6 py-4 text-sm font-bold text-slate-500">תאריך</th>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <th className="px-6 py-4 text-sm font-bold text-slate-500">מיקום</th>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <th className="px-6 py-4 text-sm font-bold text-slate-500 text-center">אורחים</th>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <th className="px-6 py-4 text-sm font-bold text-slate-500 text-center">סטטוס</th>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </thead>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <tbody className="divide-y divide-neutral-50">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {requests.map(req => <EventItem key={req.id} event={req} onSelect={setSelectedEvent} />)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </tbody>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </table>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ) : (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <Calendar
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            localizer={localizer}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          events={calendarEvents}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        startAccessor="start"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      endAccessor="end"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    onSelectEvent={(event: any) => setSelectedEvent(event.resource)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  eventPropGetter={(event: any) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const statusClass = `status-${event.resource.status}`;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  return { className: statusClass };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              messages={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              next: "הבא", previous: "הקודם", today: "היום", month: "חודש", week: "שבוע", day: "יום", agenda: "אג'נדה", date: "תאריך", time: "שעה", event: "אירוע", noEventsInRange: "אין אירועים בטווח זה.", showMore: total => `+${total}`
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {/* --- Modal --- */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {selectedEvent && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div onClick={() => setSelectedEvent(null)} className="fixed inset-0 bg-black/30 flex items-center justify-center z-50 transition-opacity">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div onClick={e => e.stopPropagation()} className="bg-white p-8 rounded-2xl shadow-2xl max-w-md w-full text-right transform transition-all">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="flex justify-between items-start">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <h2 className="text-2xl font-bold mb-1 text-slate-800">{selectedEvent.customerName}</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <p className="text-slate-500">{selectedEvent.location}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <span className={`px-3 py-1.5 text-xs font-bold rounded-full ring-1 ring-inset ${statusStyles[selectedEvent.status]}`}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {statusTranslations[selectedEvent.status]}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="my-6 border-t border-slate-100"></div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="space-y-4 text-sm">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p><strong>תאריך:</strong> {new Date(selectedEvent.eventDate).toLocaleDateString('he-IL')}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p><strong>מספר אורחים:</strong> {selectedEvent.guestCount}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p><strong>אימייל:</strong> {selectedEvent.email}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p><strong>טלפון:</strong> {selectedEvent.phone}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="mt-8 flex justify-end gap-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <button onClick={() => setSelectedEvent(null)} className="px-5 py-2.5 rounded-lg text-sm font-semibold text-gray-700 bg-gray-100 hover:bg-gray-200">סגור</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {selectedEvent.status === 'pending' && 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <button onClick={handleConfirmEvent} className="px-5 py-2.5 rounded-lg text-sm font-semibold text-white bg-green-500 hover:bg-green-600">אשר אירוע ושלח מייל</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    export default AdminDashboard;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    